version: "3"
services:
  control4-test-web:
    restart: always
    container_name: control4-test
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
     - 4444:4444
    volumes:
     - .:/usr/app
